---
- name: Fase 3 - Configurazione del Control Plane (K3s Server)
  hosts: k3s_server
  become: yes
  tasks:
    - name: Assicurati che i driver NFS siano installati (Prerequisito Storage)
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes
      register: apt_status
      until: apt_status is success
      retries: 15
      delay: 10

    - name: Scarica ed installa K3s in modalita' Server
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /etc/systemd/system/k3s.service

    - name: Attendi la generazione del Node Token
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        state: present
        timeout: 60

    - name: Estrai il Node Token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token_cmd
      changed_when: false

- name: Fase 3 - Configurazione del Worker Node (K3s Agent)
  hosts: k3s_agent
  become: yes
  tasks:
    - name: Assicurati che i driver NFS siano installati (Prerequisito Storage)
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes
      register: apt_status
      until: apt_status is success
      retries: 15
      delay: 10

    - name: Scarica ed installa K3s in modalita' Agent (senza avviarlo)
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | 
        INSTALL_K3S_SKIP_START=true
        K3S_URL=https://{{ hostvars[groups['k3s_server'][0]]['ansible_host'] }}:6443 
        K3S_TOKEN={{ hostvars[groups['k3s_server'][0]]['k3s_token_cmd']['stdout'] }} sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service

    - name: Avvia e abilita il servizio K3s Agent in modo sicuro
      ansible.builtin.systemd:
        name: k3s-agent
        state: started
        enabled: yes
        daemon_reload: yes