[proxmox]
proxmox ansible_host=192.168.1.222 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[tailscale_lxc]
tailscale_lxc ansible_host=192.168.1.203 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[nfs_lxc]
nfs_server ansible_host=192.168.1.206 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[k3s_server]
k3s_master ansible_host=192.168.1.217 ansible_user=kubeuser ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[k3s_agent]
k3s_worker ansible_host=192.168.1.218 ansible_user=kubeuser ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'
