[proxmox]
proxmox ansible_host=192.168.1.222 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[nfs_lxc]
192.168.1.202 ansible_user=root

[tailscale_lxc]
tailscale_lxc ansible_host=192.168.1.201 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'
