---
- name: Recupero Informazioni Iniziali Proxmox
  hosts: proxmox
  gather_facts: false

  tasks:
    - name: Interroga Proxmox per individuare gli storage abilitati ai Template (vztmpl)
      ansible.builtin.shell: "pvesm status -content vztmpl | awk 'NR>1 {print $1}'"
      register: available_template_storage
      changed_when: false
      tags: ['storages']

    - name: Interroga Proxmox per individuare gli storage abilitati ai Dischi LXC (rootdir)
      ansible.builtin.shell: "pvesm status -content rootdir | awk 'NR>1 {print $1}'"
      register: available_disk_storage
      changed_when: false
      tags: ['storages']

    - name: Chiedi a Proxmox il prossimo VMID disponibile
      ansible.builtin.command: pvesh get /cluster/nextid
      register: pve_next_vmid
      changed_when: false
      tags: ['vmid']

    - name: Salva il VMID come commento dentro vars.yml
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "../../vars.yml"
        regexp: '^lxc_vmid:'  
        line: "lxc_vmid: {{ pve_next_vmid.stdout | trim }}"
        create: yes
      tags: ['vmid']

    - name: Esporta i dati recuperati in formato JSON per la WebApp
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "../../proxmox_info.json"
        content: |
          { "template_storages": {{ available_template_storage.stdout_lines | to_json }}, "disk_storages": {{ available_disk_storage.stdout_lines | to_json }} }
      tags: ['storages']